### ISSUE TITLE
App closing after opening

### ISSUE THREAD

**Issue by fabioselau077** [nizwar/nizvpn#1]
Hello, thanks for the wonderful plugin.
I cloned your repository and made the changes and when I run it through VSCode it opens normally in the emulator.
However, when I generate the apk (flutter build apk --release) the generated apk installed in the emulator when opened is closed automatically.
The apk in debug mode (flutter build apk --debug) is the same.
But why does this happen only with the apk and when I run through vscode everything works perfectly?
The change I made to the android folder was to change the package name.

Edit:Without changing anything in the project, the same thing happens

**Comment by nizwar** [comment]
Hi sorry for super late response, can you show me the errors that you got, if it not shown on debug console, you can use `adb logcat`
