### ISSUE TITLE
how to run it with openvpn.net?

### ISSUE THREAD

**Issue by Jazzykhan** [nizwar/nizvpn#3]

**Comment by Jazzykhan** [comment]
where does this came from?
id.nizwar.nvpn/vpnstage
and other two links

**Comment by nizwar** [comment]
id.nizwar.nvpn/vpnstage and the others was the Channel's name, simple way is i call a function from native that attach with those "links", here i got a reference about this https://flutter.dev/docs/development/platform-integration/platform-channels#example-client
